name: Create Azure Service Bus Namespace

on:
  push:
    branches:
      - main

jobs:
  create_service_bus_namespace:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure PowerShell
        uses:  actions/setup-pwsh@v2
        with:
          azPSVersion: 'LatestVersion'

      - name: Login to Azure
        run: |
          $azurePassword = ConvertTo-SecureString "Kranti@2024" -AsPlainText -Force
          $azureCredential = New-Object System.Management.Automation.PSCredential("pradeep.somas@hcl.com", $azurePassword)
          Connect-AzAccount -Credential $azureCredential -TenantId "189de737-c93a-4f5a-8b68-6f4ca9941912"

      - name: Create Service Bus Namespace
        run: |
          $resourceGroupName = "powerautomat"
          $namespaceName = "TestNamespace"
          $location = "East US"
          New-AzServiceBusNamespace -ResourceGroupName $resourceGroupName -NamespaceName $namespaceName -Location $location
