name: Create Service Bus Namespace

on:
  push:
    branches:
      - main

jobs:
  create_namespace:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Log in to Azure
        run: |
          az login --username $AZURE_USERNAME --password $AZURE_PASSWORD
          
      - name: Create Azure Service Bus Namespace
        run: |
          az servicebus namespace create --name TestNamespace --resource-group powerautomat --location eastus
